[connections.supabase]
url = "https://xakyoixpmvzsyyvgvari.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhha3lvaXhwbXZ6c3l5dmd2YXJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcxNjI3MDIsImV4cCI6MjA4MjczODcwMn0.y2-dyHqXvPavyQ7vdDJCu4McW_0LFtbjPm_psA6vL0Q"
